name: Generate test env build
on: 
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    environment: STAGING
    steps:
      - uses: actions/checkout@v3
      
      - name: Install npm dependencies
        run: echo ${env.ENVIRONMENT}



